version: "3.9"

services:
  db:
    image: postgres:15-alpine
    container_name: rag_day_2_db
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 'ujjwal@!23'
      POSTGRES_DB: mydatabase
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  app:
    build: .
    container_name: rag_day_2_app
    env_file:
      - .env
    environment:
      DATABASE_URL: 'postgresql://postgres:ujjwal@!23@db:5432/mydatabase'
    depends_on:
      - db
    ports:
      - "8000:8000"
    volumes:
      - .:/app:cached
    restart: unless-stopped
    command: uvicorn main:app --host 0.0.0.0 --port 8000

volumes:
  pgdata:
    driver: local
